export { ModalsManager } from './modals/ModalsManager';
export { MessageRenderer } from './chat/MessageRenderer';
export { ChatModule } from './chat/ChatModule';
export { SearchModule } from './search/SearchModule';
export { SidebarModule } from './sidebar/SidebarModule';
export { VoiceModule } from './voice/VoiceModule';
export { DocumentManager } from './document/DocumentManager';
export { ProfileModule } from './profile/ProfileModule';
export { SettingsModule } from './settings/SettingsModule';
export { StreamModule } from './stream/StreamModule';
export { StatsModule } from './stats/StatsModule';
export { SettingsView } from './settings/SettingsView';
export { SettingsController } from './settings/SettingsController';
export { ChatController } from './chat/ChatController';
export { ThinkingAnimator } from './chat/ThinkingAnimator';
export { VoiceController } from './voice/VoiceController';
export { LicenseModule } from './license/LicenseModule';
export { ModelsModule } from './models/ModelsModule';
export { SuggestionsService } from './suggestions/SuggestionsService';
export { AboutModule } from './about/AboutModule';
export { LegalModule } from './legal/LegalModule';
export { HelpModule } from './help/HelpModule';
export { ContactModule } from './contact/ContactModule';
export { WebPermissionGate, WebIntentService } from './web';
export type { WebIntentResult, WebGateDecision } from './web';
export { handleCopyTableClick, tableElementToTsv } from './markdown';
export { UpdateManager, updateManager } from './updater';
export type { UpdateInfo } from './updater';
