/**
 * ShellHost — Contract for widget shell rendering (implemented by App).
 */
import type { AppSettings, LLMModel, UserMemory, RAGDocument, MessageSearchResult } from '../../types';
import type { ProfilePublic } from '../profile/ProfileModule';
import type { ChatModule } from '../chat/ChatModule';
import type { SidebarModule } from '../sidebar/SidebarModule';
import type { StreamModule } from '../stream/StreamModule';
import type { StatsModule } from '../stats/StatsModule';
import type { ProfileModule } from '../profile/ProfileModule';
import type { VoiceModule } from '../voice/VoiceModule';
import type { LicenseModule } from '../license/LicenseModule';
import type { DocumentManager } from '../document/DocumentManager';
import type { WidgetMode } from '../../constants/widgetMode';

export interface ShellHost {
  settings: AppSettings;
  mode: WidgetMode;
  sidebarOpen: boolean;
  settingsOpen: boolean;
  pinned: boolean;
  isConnected: boolean;
  models: LLMModel[];
  webSearchEnabled: boolean;
  webSearchPrivacyAccepted: boolean;
  searchQuery: string;
  messageSearchResults: MessageSearchResult[];
  ragDocuments: RAGDocument[];
  userMemories: UserMemory[];
  activeProfile: ProfilePublic | null;
  chatModule: ChatModule;
  sidebarModule: SidebarModule;
  streamModule: StreamModule;
  statsModule: StatsModule;
  profileModule: ProfileModule;
  voiceModule: VoiceModule;
  licenseModule: LicenseModule;
  documentManager: DocumentManager;
  escapeText(text: string): string;
  renderConversationList(): string;
  renderEmptyChat(): string;
  renderMessages(): string;
  renderSettings(): string;
  attachSettingsEvents(): void;
  attachVoiceEvents(): void;
  getQuotaBadgeClass(): string;
  getQuotaLabel(): string;
  getQuotaTooltip(): string;
  checkFeatureAccess(feature: 'voice' | 'rag' | 'memory' | 'search' | 'pro'): boolean;
  promptLicense(tier: 'lite' | 'pro'): void;
  showWebPrivacyModal(context?: 'pre-generate' | 'post-refusal'): void;
  hideWebPrivacyModal(): void;
  generateResponse(): Promise<void>;
  refreshConvList(): void;
  setMode(mode: WidgetMode): Promise<void>;
  togglePin(): Promise<void>;
  toggleSettings(open: boolean): void;
  newConversation(): Promise<void>;
  openConversation(id: string): Promise<void>;
  deleteConversation(id: string): Promise<void>;
  sendMessage(): Promise<void>;
  copyMessage(id: string): Promise<void>;
  regenerateMessage(id: string): Promise<void>;
  editMessage(id: string): Promise<void>;
  renderCompactSuggestions(): string;
  toggleWebSearch(): void;
  syncWebToggleButtons(): void;
  openExportMenu(anchor?: HTMLElement): void;
  openModelSwitcher(anchorEl: HTMLElement): void;
  setLanguage(lang: string): Promise<void>;
  refreshConnection(): Promise<void>;
  refreshModels(): Promise<void>;
  toast(text: string, type?: 'success' | 'error' | 'info' | 'warning'): void;
  hideConfirm(): void;
  renderAttachmentBar(): void;
  getVisionAttachOptions(): { visionMode?: boolean };
  setupResizeHandle(): void;
  autoResizeTextarea(): void;
  renderMessagesView(): void;
  getRootElement(): HTMLElement;
  getChatContainer(): HTMLElement | null;
  getChatInput(): HTMLTextAreaElement | null;
  setChatContainer(el: HTMLElement | null): void;
  setChatInput(el: HTMLTextAreaElement | null): void;
}
